"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[hostname]
ssh_only = false

[shell]
disabled = false

[python]
disabled = true

[gcloud]
disabled = true
