call pathogen#infect()

let g:ruby_path=":C:\ruby193\bin"

set backupdir=$TEMP,$TMP,.
set directory=$TEMP,$TMP,.

set number      " Line numbers
set ruler       " Show current line number and char
set backspace=2 " Conventional backspace behaviour
set scrolloff=3

syntax on
filetype plugin indent on

set tabstop=4 shiftwidth=4 smarttab
set autoindent smartindent

autocmd FileType c set expandtab " For CSE
autocmd BufEnter *.nxc setf nqc | set cindent

" Cygwin-specific settings
if has("win32unix")
  " Block cursor
  let &t_ti.="\e[1 q"
  let &t_SI.="\e[5 q"
  let &t_EI.="\e[1 q"
  let &t_te.="\e[0 q"

  " 256 colours
  let &t_Co=256
  let &t_AF="\e[38;5;%dm"
  let &t_AB="\e[48;5;%dm"
endif

" Colorscheme
if &t_Co >= 256
  let g:molokai_original=1
  colorscheme molokai
else
  colorscheme torte
endif

" GUI settings
if has("gui_running")
  set guioptions-=m
  set guioptions-=T

  command MS set guioptions+=m
  command MH set guioptions-=m

  if has("gui_gtk2")
    set guifont=Inconsolata\ 11
  elseif has("gui_win32")
    set guifont=Consolas:h10:cANSI
  endif
endif

" Tab autocompletion - from https://gist.github.com/3418565
function! Tab_Or_Complete()
  if col('.')>1 && strpart( getline('.'), col('.')-2, 3 ) =~ '^\w'
    return "\<C-N>"
  else
    return "\<Tab>"
  endif
endfunction
inoremap <Tab> <C-R>=Tab_Or_Complete()<CR>
